---
- hosts: alisson
  tasks:
    - name: Creating VirtualBox VM
      shell: vboxmanage clonevm BaseUbuntu14 --name VMScaling --register
    - name: StartVM
      shell: vboxmanage startvm VMScaling
